travis:
  secure:
    BINSTAR_TOKEN: sIt5RgdFQ/yIUFJRHfMVTjcJ4tMqZZlpYlZmkX4YPgVj2U1zptz9apjQknEm2xIvY6m5RMqJQmphG8N3UbCWl6juP2OV+lE56Thxox18NhsJ/Tkj9mNUELZTL8gIjJfEeEjb9wTp2Yfgg/uFPYPRA0foMKpXgKHK9Mfbint2fr2reCiP/0JQbVeS7MaIY6HdM14IWpW/zF/bBkJLK3VyGM74m30dIn8QgXu9U5uIsLK1CNnKx3gcTwxIsxuKoFCCQGY1VUBkVVLUUnU7cCfHELt9iAXZrMGY1A0Iun3VVAv1llRBPo29nCkrgoG+BKX1zH1XoWtPKlS/TFQAprYIgWlfHomd4sdUuor0K5sukfBxEMbcybCR7Cwt17f3L7Cs7Ad5Kyq5UpeYYGBLJxhMgfxysxlFZcMRoRlDLfUhaxVoWcRY1WGTVNYpsbOJQw8WnkMfyCorWwtXBpYHxYC9jSjq0ZW/EpTJz1bigsDae5ks8XIiN6+KlSbK77v8CLkSgE1xrtbZK5lfzF2RFlVcPxl8smRAHORmjeeq/RF45pAaasNUcxXIoRBIMDUUMTkQF1ZmjhgsVffmBI+QQEIH6PRrDuXXtNYftn1zXCIq+YzB9mdh5hOLNP75pVEfDgJwUASIDmmfjyah+aD8EnC692TUTaPnv4xwNz+sUl3/+fA=
bot:
  automerge: true
conda_forge_output_validation: true
